import React,{useState,useEffect} from 'react';
import {supabase} from './supabase-service.js';
export function exactTime(value) {return new Intl.DateTimeFormat('en-IN',{dateStyle:'medium',timeStyle:'long',timeZone:'Asia/Kolkata'}).format(new Date(value));}
const labels={status:'Status',assigned_to:'Assigned employee',department_id:'Department',type_id:'Type',subtype_id:'Subtype',requirements:'Requirements',description:'Description',priority:'Priority'};
export default function TicketTimeline({ticket,users,revision=0}) {
 const [events,setEvents]=useState([]),[error,setError]=useState(''),[more,setMore]=useState(false),[busy,setBusy]=useState(false);
 async function load(older=false){setBusy(true);setError('');try{let query=supabase.from('ticket_activity').select('*').eq('ticket_id',ticket.id).order('id',{ascending:false}).limit(31);if(older&&events.length)query=query.lt('id',events.at(-1).id);const result=await query;if(result.error)throw result.error;setMore(result.data.length>30);setEvents(previous=>older?[...previous,...result.data.slice(0,30)]:result.data.slice(0,30));}catch{setError('Unable to load activity. Please retry.');}finally{setBusy(false);}}
 useEffect(()=>{load();},[ticket.id,ticket.updated_at,revision]);
 function value(change,key){if(change.field==='assigned_to')return users.find(u=>u.id===change[key])?.name||'Employee';return String(change[key]??'None');}
 return <section className="activity-section"><h3>Activity timeline</h3><p className="hint">Exact times shown in India Standard Time (IST). Older edits before activity tracking was enabled are unavailable.</p>{error&&<p role="alert">{error} <button type="button" className="text-button" onClick={()=>load()}>Retry</button></p>}<ol className="activity-timeline">{events.map(event=><li key={event.id}><span className="activity-dot"/><div><strong>{event.action==='created'?'Ticket created':event.action==='commented'?'Comment added':event.changes.some(c=>c.field==='status')?'Status changed':'Ticket edited'}</strong><p>{event.actor_name} · <time dateTime={event.occurred_at}>{exactTime(event.occurred_at)}</time></p>{event.comment_body&&<blockquote style={{whiteSpace:'pre-wrap'}}>{event.comment_body}</blockquote>}{event.changes.map(change=><p key={change.field}>{labels[change.field]||change.field}{['status','priority','assigned_to'].includes(change.field)?`: ${value(change,'from')} → ${value(change,'to')}`:' updated'}</p>)}</div></li>)}</ol>{!events.length&&!busy&&!error&&<p>No activity yet.</p>}{busy&&<p role="status">Loading activity…</p>}{more&&<button type="button" className="secondary" disabled={busy} onClick={()=>load(true)}>Load older activity</button>}</section>;
}
