import React,{useState,useRef} from 'react';
import {exportTicketsExcel} from './ticket-export-service.js';
export default function TicketExportControls({selectedIds,departments=[],users=[],onError}){
 const lock=useRef(false),[busy,setBusy]=useState(false),[count,setCount]=useState(0),[filters,setFilters]=useState({from:'',to:'',department:'',status:'',issue:'',poc:'',team:'',sla:''});
 const dept=departments.find(d=>d.id===filters.department);const issues=[...new Set((dept?[dept]:departments).flatMap(d=>d.issues||[]))];
 const set=(key,value)=>setFilters(f=>({...f,[key]:value,...(key==='department'?{issue:'',poc:''}:{})}));
 async function run(selected){if(lock.current)return;lock.current=true;setBusy(true);setCount(0);onError('');try{await exportTicketsExcel(selected?{}:filters,selected?selectedIds:null,setCount);}catch(e){onError(e.message||'Export failed.');}finally{lock.current=false;setBusy(false);}}
 return <div style={{padding:'12px 18px',borderBottom:'1px solid #e4ebe6'}}>{selectedIds.length>0&&<button type="button" className="secondary" disabled={busy} onClick={()=>run(true)}>Export Selected (Excel)</button>}<details><summary>Export filters</summary><div className="form-grid"><label>Created from (IST)<input type="date" disabled={busy} value={filters.from} onChange={e=>set('from',e.target.value)}/></label><label>Created through (IST)<input type="date" disabled={busy} value={filters.to} onChange={e=>set('to',e.target.value)}/></label><label>Department<select disabled={busy} value={filters.department} onChange={e=>set('department',e.target.value)}><option value="">All departments</option>{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Assigned team<select disabled={busy} value={filters.team} onChange={e=>set('team',e.target.value)}><option value="">All teams</option>{departments.map(d=><option value={d.name} key={d.id}>{d.name}</option>)}</select></label><label>Status<select disabled={busy} value={filters.status} onChange={e=>set('status',e.target.value)}><option value="">All statuses</option>{['Open','In Progress','Waiting','Resolved','Completed','Closed'].map(s=><option key={s}>{s}</option>)}</select></label><label>Issue / Tool<select disabled={busy} value={filters.issue} onChange={e=>set('issue',e.target.value)}><option value="">All issues</option>{issues.map(i=><option key={i}>{i}</option>)}</select></label><label>Assigned POC<select disabled={busy} value={filters.poc} onChange={e=>set('poc',e.target.value)}><option value="">All POCs</option>{users.filter(u=>u.active!==false&&(!filters.team||u.department===filters.team)).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>SLA status<select disabled={busy} value={filters.sla} onChange={e=>set('sla',e.target.value)}><option value="">All</option><option>Not configured</option></select></label></div><button type="button" className="secondary" disabled={busy} onClick={()=>run(false)}>Export All (Excel)</button></details>{busy&&<p role="status">Preparing export · {count} tickets fetched…</p>}</div>;
}
