import React,{useState,useEffect,useRef} from 'react';
import TicketTimeline,{exactTime} from './TicketTimeline.jsx';
import {supabase,fetchTicketTimes} from './supabase-service.js';
import {workStatuses,canComplete} from './ticket-workflow.js';
export default function TicketDiscussion({ticket,user,users,onUpdate,onError}) {
 const lock=useRef(false);const [revision,setRevision]=useState(0);
 const [comments,setComments]=useState([]),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true);
 async function load(){const result=await supabase.from('ticket_comments').select('*').eq('ticket_id',ticket.id).order('created_at',{ascending:false}).limit(50);if(result.error)throw result.error;setComments(result.data.reverse());}
 useEffect(()=>{load().catch(e=>onError(e.message)).finally(()=>setLoading(false));},[ticket.id]);
 async function status(value){if(lock.current)return;lock.current=true;setBusy(true);try{const result=await supabase.from('tickets').update({status:value}).eq('id',ticket.id).eq('updated_at',ticket.updated_at).select().single();if(result.error)throw new Error(result.error.code==='PGRST116'?'This ticket changed. Refresh the page before updating its status.':result.error.message);await onUpdate({...ticket,status:result.data.status,updated_at:result.data.updated_at,...await fetchTicketTimes(ticket.id)});}catch(e){onError(e.message);}finally{lock.current=false;setBusy(false);}}
 const options=workStatuses(ticket,user);
 return <section><h3>Progress & comments</h3>{options.length>0&&<label>Update status<select disabled={busy} value={ticket.status} onChange={e=>status(e.target.value)}>{!options.includes(ticket.status)&&<option>{ticket.status}</option>}{options.map(s=><option key={s}>{s}</option>)}</select></label>}{canComplete(ticket,user)&&<button type="button" className="primary" disabled={busy} onClick={()=>status('Completed')}>Mark Completed</button>}{ticket.status==='Resolved'&&!canComplete(ticket,user)&&<p className="hint">Waiting for the ticket creator to confirm completion.</p>}{loading?<p>Loading comments…</p>:comments.length?comments.map(c=><div className="ticket-comment" key={c.id}><strong>{users.find(u=>u.id===c.author_id)?.name||'Employee'}</strong><small> · {exactTime(c.created_at)}</small><p style={{whiteSpace:'pre-wrap'}}>{c.body}</p></div>):<p className="hint">No comments yet.</p>}{ticket.status==='Completed'?<p className="notice">This ticket is completed and read-only.</p>:<form onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const body=String(new FormData(form).get('comment')).trim();if(!body||lock.current)return;lock.current=true;setBusy(true);try{const result=await supabase.from('ticket_comments').insert({ticket_id:ticket.id,author_id:user.id,body});if(result.error)throw result.error;form.reset();await load();setRevision(n=>n+1);await onUpdate({...ticket,...await fetchTicketTimes(ticket.id)});}catch(e){onError(e.message);}finally{lock.current=false;setBusy(false);}}}><label>Add a comment<textarea name="comment" required maxLength={4000} rows={3} placeholder="Share an update or ask a question…"/></label><button className="secondary" disabled={busy}>{busy?'Saving…':'Post comment'}</button></form>}<TicketTimeline ticket={ticket} users={users} revision={revision}/></section>;
}
