import React,{useState,useEffect} from 'react';
import {supabase} from './supabase-service.js';
export function duration(seconds){if(seconds==null)return '—';const minutes=Math.max(0,Math.round(Number(seconds)/60));return minutes<60?`${minutes} min`:`${Math.floor(minutes/60)}h ${minutes%60}m`;}
export default function TicketInsights(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{const r=await supabase.rpc('ticket_insights');if(r.error)throw r.error;setData(r.data);}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 return <section><div className="table-top"><h2>Service insights</h2><button className="secondary" disabled={busy} onClick={load}>{busy?'Loading…':'Refresh insights'}</button></div>{error&&<p className="error">{error}</p>}{data&&<><div className="stats">{[['First response',duration(data.average_response_seconds)],['First resolution',duration(data.average_resolution_seconds)],['Recorded downtime',duration(data.recorded_downtime_seconds)],['Awaiting response',data.awaiting_response]].map(([label,value])=><div className="stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><p className="hint">All accessible tickets, calculated in Supabase. First response is the first assignee/IT comment or status change by someone other than the creator. Resolution measures the first recorded Resolved status. Missing historic actions are excluded from averages.</p><p className="hint">Downtime measures employee-reported work blockage from ticket creation to first resolution; unresolved blockage continues accumulating. {data.active_downtime} ongoing. {data.unrecorded_downtime} tickets have no recorded downtime information.</p><section className="panel"><h3 style={{padding:'18px'}}>Ownership</h3><table><thead><tr><th>ASSIGNED EMPLOYEE</th><th>ACTIVE</th><th>TOTAL</th></tr></thead><tbody>{data.ownership.map(row=><tr key={row.owner}><td>{row.owner}</td><td>{row.active}</td><td>{row.total}</td></tr>)}</tbody></table></section><section className="panel" style={{marginTop:20}}><h3 style={{padding:'18px'}}>Recurring categories · last 90 days</h3><table><thead><tr><th>DEPARTMENT</th><th>ISSUE</th><th>AFFECTED SYSTEM</th><th>TICKETS</th></tr></thead><tbody>{data.recurring.map((row,i)=><tr key={i}><td>{row.department}</td><td>{row.type} · {row.subtype}</td><td>{row.system}</td><td>{row.occurrences}</td></tr>)}</tbody></table>{!data.recurring.length&&<p className="empty">No repeated categories recorded yet.</p>}</section><p className="hint">Repeated categories are potential recurring issues, not confirmed duplicate incidents.</p></>}</section>;
}
